### ISSUE TITLE
PPMI BIDS subject without phenotypic information

### ISSUE THREAD

**Issue by surchs** [neurodatascience/mr_proc-ppmi#12]
Hi,

I found two subjects with BIDS data, but no entry in the phenotypic bagel.csv file.

bids path on bic: `/data/pd/ppmi/bids`
bagel.csv path on bic: `/data/pd/ppmi/tabular/bagel.csv`

These are the subjects:
```
'sub-5010', 'sub-5014', 'sub-5007', 'sub-114526', 'sub-136696', 'sub-5005', 'sub-5013', 
'sub-5006', 'sub-5003', 'sub-14281', 'sub-138022', 'sub-5008', 'sub-5015', 'sub-5011', 'sub-53518', 'sub-5012', 'sub-5016', 'sub-08827APR11', 'sub-5018', 'sub-5009', 'sub-53423', 'sub-41370', 'sub-5004', 
'sub-59583', 'sub-5002', 'sub-01221JUL16', 'sub-5017', 'sub-33500000', 'sub-5001', 'sub-01218AUG16', 'sub-5000', 'sub-42001'
```

Similar to https://github.com/neurodatascience/mr_proc-qpn/issues/8

@michellewang, do you have some thoughts on this?

**Comment by michellewang** [comment]
If I remember correctly `sub-01218AUG16`/`sub-01221JUL16`/etc. are phantom subjects with no valid imaging data (`sub-33500000` also, now that I checked). @nikhil153 should we remove them from BIC?

From a quick check just now I can confirm that some of the other subjects (`5014`, `136696`) do have at least some tabular data (MoCA) for some sessions. Not sure why they're not in `bagel.csv` but maybe @nikhil153 has some thoughts

**Comment by surchs** [comment]
Oh, that makes sense. Thanks @michellewang. I don't think we want to have phantom runs in the graph, but it may be a bit much to ask to have them also removed from the BIDS directory. We should discuss what to do in this case

**Comment by nikhil153** [comment]
@michellewang - yes we can remove all phantom subjects from the mr_proc dataset. 
For the subjects with MoCA missing in the bagel.csv could be for one of these reasons.
1. They are not part of selected Dx groups (i.e. controls, SWEDD, PD, Prodromal)
2. They don't have regular visit codes that we are tracking
3. They were missed in the `mr_proc_manifest` - the one that was on disk before @michellewang updated it. 

If it's the 3rd case, then @michellewang, let me know if the new PPMI manifest is finalized and I can re-run the [bagel_generator](https://github.com/neurodatascience/mr_proc-ppmi/blob/main/notebooks/tabular_tracking.ipynb)

**Comment by alyssadai** [comment]
I believe this issue is resolved now and can be closed! 🙂
