### ISSUE TITLE
Migrate dataset specific files from `neurodatascience/mr_proc/ppmi` branch

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/mr_proc-ppmi#4]
Original issue: [neurodatascience/mr_proc#63](https://github.com/neurodatascience/mr_proc/issues/63).

- ~~`dicom_fetch.py`~~
- `heuristics.py`

@nikhil153 I don't see a `dicom_fetch.py` in https://github.com/neurodatascience/mr_proc/tree/ppmi/workflow/dicom_org. Is it needed for PPMI?

**Comment by nikhil153** [comment]
@michellewang `dicom_fetch.py` was written for QPN. Presumably, you could write something similar to download and organize PPMI data into `scratch/raw_dicom`.

**Comment by michellewang** [comment]
@nikhil153 okay, for now I've been doing the downloads manually. [`livingpark_utils`](https://github.com/LivingPark-MRI/livingpark-utils) has a function to download imaging data, though only T1s and only by subject ID, which is not ideal for our purposes (it also requires Chrome which doesn't seem to be available on BIC as far as I can tell). Another issue is that the PPMI website seems to change relatively often, so I'm not sure if it would be a good idea to try to use a web scraper to automatically download the images.

Maybe a way to try to automate the DICOM download as much as possible would be to:
1. Have a script that generates a list of image ID strings for files to download (this could be by checking what's on disk and comparing with the manifest)
2. Manually copy that list into the LONI search tool, create the collection, and get the download links
3. Run another script that downloads the zip files and unzips them

What do you think?
